CREATE TABLE IF NOT EXISTS website_members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL,
    name VARCHAR(255) NOT NULL,
    id_number VARCHAR(100) NOT NULL,
    role_title VARCHAR(255) NOT NULL,
    specialty VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    achievements TEXT NULL,
    awards TEXT NULL,
    qr_image_path VARCHAR(255) NULL,
    photo_path VARCHAR(255) NULL,
    photo_description TEXT NULL,
    gallery_json LONGTEXT NULL,
    is_published TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_website_member_user (user_id),
    UNIQUE KEY uq_website_member_id_number (id_number)
);
